//! RINEX compression / decompression module
use thiserror::Error;

// TODO
// Improve Result<> IoError/Error relation ship
// the current User API .read().error()
// Will trigger a string comparison on every single .read() acces veritication

mod compressor;
mod crinex;
mod decompressor;
mod numdiff;
mod obs;
mod textdiff;

pub use compressor::Compressor;
pub use crinex::CRINEX;

pub use decompressor::{Decompressor, DecompressorExpert};

pub(crate) use numdiff::NumDiff;
pub(crate) use obs::ObsDiff;
pub(crate) use textdiff::TextDiff;

use std::io::{Error as IoError, ErrorKind};

/// Hatanaka dedicated Errors
#[derive(Debug)]
pub enum Error {
    /// Buffer too small to accept incoming data
    BufferOverflow,
    /// Failed to read CRINEX PROG/DATE
    CrinexParsing,
    /// Forwarded Epoch description does not look good: Invalid RINEX!
    EpochFormat,
    /// Forwarded content is not consisten with CRINEX V1
    BadV1Format,
    /// Forwarded content is not consisten with CRINEX V3
    BadV3Format,
    /// Recovered Epoch descriptor (in the decompression scheme)
    /// does not look good. Most likely due to invalid content
    /// generated by the decompressor: should never happen
    RecoveredEpochFormat,
    /// Recovered or forwarded SV description is incorrect (bad data)
    SVFormat,
    /// [SV] identification error: bad relationship between
    /// either:
    ///   - recovered Epoch description (in decompression scheme)
    ///   and parsing process
    ///   - invalid data being forwared and/or incompatibility
    ///   with previously formwared Header
    SVParsing,
    /// It is mandatory that the CRINEX version be correctly defined
    /// so we can parse it and adapt the (de-)compression scheme
    VersionParsing,
    /// Keep reading: need more data to progress (FSM stuck)
    NeedMoreData,
}
